---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bookstore
  name: bookstore
spec:
  containers:
  - image: quay.io/sjfke/bookstore:1.0
    name: bookstore
    ports:
    - containerPort: 8080
      hostPort: 8080
