---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstoredb
spec: # https://mariadb.org/start-mariadb-in-k8s/
  replicas: 1
  selector:
    matchLabels:
      app: bookstoredb
  template: 
    metadata:
      labels:
        app: bookstoredb
    spec: 
      containers:
      - name: bookstoredb
        image: docker.io/library/mariadb:latest
        ports:
        - containerPort: 3306 
          hostPort: 3306
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "1" # if it is 1 and root_password is set, 
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: db_root_password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: jsp_bookstoredata-pvc
      volumes:
      - name: jsp_bookstoredata-pvc
        persistentVolumeClaim:
          claimName: jsp_bookstoredata
