---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bookstoredb
  name: bookstoredb
spec:
  containers:
  - env:
    - name: MARIADB_ROOT_PASSWORD
      value: r00tpa55
    image: docker.io/library/mariadb:latest
    name: bookstoredb
    ports:
    - containerPort: 3306
      hostPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: jsp_bookstoredata-pvc
  volumes:
  - name: jsp_bookstoredata-pvc
    persistentVolumeClaim:
      claimName: jsp_bookstoredata
