apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec: # https://mariadb.org/start-mariadb-in-k8s/
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template: 
    metadata:
      labels:
        app: mariadb
    spec: 
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306 
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "0" # if it is 1 and root_password is set, 
        - name: MARIADB_ROOT_PASSWORD
          value: secret
