# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-01-24T12:06:25Z"
  labels:
    app: registry-pod
  name: registry-pod-deployment
spec:
  selector:
    matchLabels:
      app: registry-pod
  template:
    metadata:
      creationTimestamp: "2024-01-24T12:06:25Z"
      labels:
        app: registry-pod
      name: registry-pod
    spec:
      containers:
      - args:
        - /etc/docker/registry/config.yml
        image: docker.io/library/registry:2.8.3
        name: registry
        ports:
        - containerPort: 5000
          hostPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: c99ef13743fb4269e38554504037e83e1602dd6f42e09f55a8af2e62f164270b-pvc
      volumes:
      - name: c99ef13743fb4269e38554504037e83e1602dd6f42e09f55a8af2e62f164270b-pvc
        persistentVolumeClaim:
          claimName: c99ef13743fb4269e38554504037e83e1602dd6f42e09f55a8af2e62f164270b
