# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/adminer-1-podified: container
    io.kubernetes.cri-o.SandboxID/adminer-1-podified: 20d106e045c70d7c0eeda284a16fff7933b29c851ecf2fc7e0f30d5040bec44
    io.podman.annotations.autoremove/adminer-1-podified: "FALSE"
    io.podman.annotations.init/adminer-1-podified: "FALSE"
    io.podman.annotations.privileged/adminer-1-podified: "FALSE"
    io.podman.annotations.publish-all/adminer-1-podified: "FALSE"
  creationTimestamp: "2023-02-06T15:02:55Z"
  labels:
    app: adminer-pod
  name: adminer-pod
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - php
    - -S
    - '[::]:8080'
    - -t
    - /var/www/html
    env:
    - name: HOSTNAME
      value: 17b486501aa0
    - name: HOME
      value: /home/adminer
    image: docker.io/library/adminer:latest
    name: adminer-1-podified
    ports:
    - containerPort: 8080
      hostPort: 8397
    resources: {}
    securityContext:
      capabilities: {}
  enableServiceLinks: false
  hostname: adminer-pod
  restartPolicy: Never
status: {}

