---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bookstoredb
  name: bookstoredb
spec: # https://mariadb.org/start-mariadb-in-k8s/
  containers:
  - envFrom:
      - configMapRef:
        name: MARIADB_ROOT_PASSWORD
    image: docker.io/library/mariadb:latest
    name: bookstoredb
    ports:
    - containerPort: 3306
      hostPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: jsp_bookstoredata-pvc
  volumes:
  - name: jsp_bookstoredata-pvc
    persistentVolumeClaim:
      claimName: jsp_bookstoredata
