# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-04T18:06:54Z"
  labels:
    app: tomcat-containersadminer1-pod
  name: tomcat-containersadminer1-pod
spec:
  ports:
  - name: "8080"
    nodePort: 32761
    port: 8080
    targetPort: 8080
  selector:
    app: tomcat-containersadminer1-pod
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-11-04T18:06:54Z"
  labels:
    app: tomcat-containersadminer1-pod
  name: tomcat-containersadminer1-pod-deployment
spec:
  selector:
    matchLabels:
      app: tomcat-containersadminer1-pod
  template:
    metadata:
      annotations:
        io.podman.annotations.ulimit: nofile=1048576:1048576,nproc=15433:15433
      creationTimestamp: "2023-11-04T18:06:54Z"
      labels:
        app: tomcat-containersadminer1-pod
      name: tomcat-containersadminer1-pod
    spec:
      containers:
      - args:
        - php
        - -S
        - '[::]:8080'
        - -t
        - /var/www/html
        env:
        - name: ADMINER_DEFAULT_SERVER
          value: bookstoredb
        - name: ADMINER_DESIGN
          value: dracula
        image: docker.io/library/adminer:latest
        name: tomcat-containersadminer1
        ports:
        - containerPort: 8080
        securityContext: {}
